### ISSUE TITLE
Get basic UT2004 examples working again

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#131]
The UT2004 hasn't changed in years, so why doesn't it work now? It's true that there were issues with the results this code produced, but it should at least run smoothly and evolve game agents. Get the original examples to work again ... see how they run on different systems.

**Comment by schrum2** [comment]
I suspect that some aspect of the Pogamut code is incompatible with the latest version of Java. Here is the exception:

FatalErrorEvent[
    Component:  UT2004SyncLockableWorldView
    Message:    Exception raising event WorldObjectUpdatedEvent[id = SELF_DM-TrainingDay.ObservedRemoteBot4, object = InfoMessage[SelfMessage][Id = WorldObjectId[SELF_DM-TrainingDay.ObservedRemoteBot4] | BotId = WorldObjectId[DM-TrainingDay.ObservedRemoteBot4] | Name = Anton | Vehicle = false | Location = [2014.00; -2060.00; -79.54] | Velocity = [0.00; 0.00; 0.00] | Rotation = [0.00; 16095.00; 0.00] | Team = 255 | Weapon = DM-TrainingDay.AssaultRifle | Shooting = false | Health = 100 | PrimaryAmmo = 100 | SecondaryAmmo = 4 | Adrenaline = 0 | Armor = 0 | SmallArmor = 0 | AltFiring = false | Crouched = false | Walking = false | FloorLocation = [2014.00; -2060.00; -127.50] | FloorNormal = [0.00; 0.00; 1.00] | Combo = None | UDamageTime = 0.0 | Action = null | EmotLeft = null | EmotCenter = null | EmotRight = null | Bubble = null | Anim = null | ][Id = WorldObjectId[SELF_DM-TrainingDay.ObservedRemoteBot4] | BotId = WorldObjectId[DM-TrainingDay.ObservedRemoteBot4] | Name = Anton | Vehicle = false | Location = [2014.00; -2060.00; -79.54] | Velocity = [0.00; 0.00; 0.00] | Rotation = [0.00; 16095.00; 0.00] | Team = 255 | Weapon = DM-TrainingDay.AssaultRifle | Shooting = false | Health = 100 | PrimaryAmmo = 100 | SecondaryAmmo = 4 | Adrenaline = 0 | Armor = 0 | SmallArmor = 0 | AltFiring = false | Crouched = false | Walking = false | FloorLocation = [2014.00; -2060.00; -127.50] | FloorNormal = [0.00; 0.00; 1.00] | Combo = None | UDamageTime = 0.0 | Action = null | EmotLeft = null | EmotCenter = null | EmotRight = null | Bubble = null | Anim = null | ], time=340]
    Cause:      class java.lang.ClassCastException: cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType cannot be cast to java.lang.Comparable (at java.util.TreeMap.getEntry(Unknown Source))
    Stacktrace:
        cz.cuni.amis.pogamut.base.component.controller.ComponentController.fatalError(ComponentController.java:518)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.raiseEvent(EventDrivenWorldView.java:106)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.objectUpdated(EventDrivenWorldView.java:188)
        cz.cuni.amis.pogamut.base3d.worldview.impl.VisionWorldView.objectCreated(VisionWorldView.java:199)
        cz.cuni.amis.pogamut.base3d.worldview.impl.VisionWorldView.objectUpdatedEvent(VisionWorldView.java:152)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.innerNotify(EventDrivenWorldView.java:125)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.notify(EventDrivenWorldView.java:225)
        cz.cuni.amis.pogamut.base3d.worldview.impl.BatchAwareWorldView.notify(BatchAwareWorldView.java:89)
        cz.cuni.amis.pogamut.ut2004.communication.worldview.UT2004SyncLockableWorldView.notify(UT2004SyncLockableWorldView.java:265)
        cz.cuni.amis.pogamut.base.communication.mediator.impl.Mediator$Worker.run(Mediator.java:327)
        java.lang.Thread.run(Unknown Source)
    Caused by: class java.lang.ClassCastException: cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType cannot be cast to java.lang.Comparable (at java.util.TreeMap.getEntry(Unknown Source))
        java.util.TreeMap.getEntry(Unknown Source)
        java.util.TreeMap.containsKey(Unknown Source)
        edu.utexas.cs.nn.tasks.ut2004.bots.GameDataCollector$10.notify(GameDataCollector.java:277)
        edu.utexas.cs.nn.tasks.ut2004.bots.GameDataCollector$10.notify(GameDataCollector.java:1)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.AbstractWorldView$ListenerNotifier.notify(AbstractWorldView.java:99)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.AbstractWorldView$ListenerNotifier.notify(AbstractWorldView.java:78)
        cz.cuni.amis.utils.listener.Listeners.notify(Listeners.java:321)
        cz.cuni.amis.utils.listener.ListenersMap.notify(ListenersMap.java:105)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.AbstractWorldView.notifyLevelCListeners(AbstractWorldView.java:693)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.AbstractWorldView.innerRaiseEvent(AbstractWorldView.java:738)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.AbstractWorldView.raiseEvent(AbstractWorldView.java:637)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.raiseEvent(EventDrivenWorldView.java:104)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.objectUpdated(EventDrivenWorldView.java:188)
        cz.cuni.amis.pogamut.base3d.worldview.impl.VisionWorldView.objectCreated(VisionWorldView.java:199)
        cz.cuni.amis.pogamut.base3d.worldview.impl.VisionWorldView.objectUpdatedEvent(VisionWorldView.java:152)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.innerNotify(EventDrivenWorldView.java:125)
        cz.cuni.amis.pogamut.base.communication.worldview.impl.EventDrivenWorldView.notify(EventDrivenWorldView.java:225)
        cz.cuni.amis.pogamut.base3d.worldview.impl.BatchAwareWorldView.notify(BatchAwareWorldView.java:89)
        cz.cuni.amis.pogamut.ut2004.communication.worldview.UT2004SyncLockableWorldView.notify(UT2004SyncLockableWorldView.java:265)
        cz.cuni.amis.pogamut.base.communication.mediator.impl.Mediator$Worker.run(Mediator.java:327)
        java.lang.Thread.run(Unknown Source)
]

This is the focal point, I believe:
Cause:      class java.lang.ClassCastException: cz.cuni.amis.pogamut.ut2004.communication.messages.ItemType cannot be cast to java.lang.Comparable (at java.util.TreeMap.getEntry(Unknown Source))

Need to look for this file
