### ISSUE TITLE
DefendCenter fitness functions (multiobjective)

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#202]
Break up the components of the Reward function in the Defend Center task into two:
one fitness function for time alive, and another for number of targets hit. Try to maximize both.

Also track the original reward function as an "other" score.

**Comment by Serenamidori** [comment]
Just double checking this wording, you want only two fitness functions and the old "score" is now the other? I'll be doing this unless you want me to change it back

**Comment by Serenamidori** [comment]
Update: tested this with DefendCenter smudged and row, but we'll probably want to double check inputs and correct code tomorrow.

**Comment by Serenamidori** [comment]
Testing this again, given that HyperNEAT wasn't working

**Comment by Serenamidori** [comment]
Quick note, getting an error when trying to watch postBestObjectives for moSmudgedRow DefendCenter, but it looks like it's learning. We'll need to fix it to be sure though, and I'm not sure how to go about testing what wrong.

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.NullPointerException: String is null
        at sun.java2d.SunGraphics2D.drawString(Unknown Source)
        at edu.utexas.cs.nn.evolution.lineage.Offspring.fillInputs(Offspring.jav
a:1584)
        at edu.utexas.cs.nn.evolution.lineage.Offspring.fillInputs(Offspring.jav
a:1553)
        at edu.utexas.cs.nn.evolution.lineage.Offspring.fillInputs(Offspring.jav
a:1544)
        at edu.utexas.cs.nn.tasks.LonerTask$EvaluationThread.call(LonerTask.java
:110)
        at edu.utexas.cs.nn.tasks.LonerTask.evaluateOne(LonerTask.java:179)
        at edu.utexas.cs.nn.experiment.ObjectiveBestNetworksExperiment.run(Objec
tiveBestNetworksExperiment.java:53)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.run(MMNEAT.java:681)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:846)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.main(MMNEAT.java:806)

**Comment by Serenamidori** [comment]
Error was corrected, sensor labels are printing out correctly and VizDoom DefendCetner is working well
