### ISSUE TITLE
Incremental evolution: map size increase with HyperNEAT

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#348]
One of the really cool things about HyperNEAT is that an evolved CPPN can create substrate networks of arbitrary sizes. They encode knowledge at infinite resolution, so as long as their knowledge generalizes, you can transfer things you learn on small maps to large maps. Note that regular NEAT is NOT capable of this ... NEAT networks evolve with a set number of inputs, so if your evaluation function inputs depend on the map size, your NEAT results can only be used on maps of a given size.

However, HyperNEAT CPPNs can make substrate networks of different sizes. The sensible thing to do is to use incremental evolution to start evolving evaluation functions for small maps, but then switch to a larger map every 50 generations or so (may need to tweak that number). You can read of an example of this approach being used in this paper:
http://eplex.cs.ucf.edu/papers/verbancsics_gecco10.pdf

**Comment by schrum2** [comment]
Since mapSequence is a class name, please capitalize the m in Map

**Comment by alicequint** [comment]
java.lang.IndexOutOfBoundsException: Index: 129, Size: 129
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at edu.utexas.cs.nn.networks.hyperneat.HyperNEATUtil.drawCoord(HyperNEATUtil.java:250)
	at edu.utexas.cs.nn.networks.hyperneat.HyperNEATUtil.drawSubstrate(HyperNEATUtil.java:215)
	at edu.utexas.cs.nn.networks.hyperneat.HyperNEATUtil.drawSubstrates(HyperNEATUtil.java:186)
	at edu.utexas.cs.nn.networks.TWEANN.animateSubstrate(TWEANN.java:837)
	at edu.utexas.cs.nn.networks.TWEANN.process(TWEANN.java:737)
	at edu.utexas.cs.nn.tasks.microrts.evaluation.NN2DEvaluationFunction.evaluate(NN2DEvaluationFunction.java:67)
	at micro.ai.mcts.uct.UCT.monteCarloRun(UCT.java:158)
	at micro.ai.mcts.uct.UCT.computeDuringOneGameFrame(UCT.java:142)
	at micro.ai.mcts.uct.UCT.getAction(UCT.java:104)
	at edu.utexas.cs.nn.tasks.microrts.MicroRTSUtility.oneEval(MicroRTSUtility.java:45)
	at edu.utexas.cs.nn.tasks.microrts.MicroRTSTask.oneEval(MicroRTSTask.java:186)
	at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:103)
	at edu.utexas.cs.nn.tasks.LonerTask$EvaluationThread.call(LonerTask.java:139)
	at edu.utexas.cs.nn.tasks.LonerTask.evaluateAll(LonerTask.java:254)
	at edu.utexas.cs.nn.evolution.mulambda.MuLambda.processChildren(MuLambda.java:240)
	at edu.utexas.cs.nn.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:380)
	at edu.utexas.cs.nn.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:214)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.run(MMNEAT.java:766)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:934)
	at edu.utexas.cs.nn.MMNEAT.MMNEAT.main(MMNEAT.java:894)

seems like its making a subsrate of the correct size, but not re-drawing it correctly

**Comment by schrum2** [comment]
Similar to #347, MapSequence should be an interface. Move the code you currently have into a class that implements this interface. Call the class something like DefaultMapSequence or BasicMapSequence.

**Comment by schrum2** [comment]
This issue can't close until MapSequence becomes an interface rather than a class with a static method. See TODO comments in MapSequence.

**Comment by schrum2** [comment]
Once we have evidence of a population that successfully evolves through several maps of increasing size, you can close this issue.
