### ISSUE TITLE
microRTS crash at gen 20:  Issue with enemy sequence

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#385]
Here is the stack trace:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 400
        at edu.utexas.cs.nn.tasks.microrts.iterativeevolution.CompetitiveEnemySequence.getAppropriateEnemy(CompetitiveEnemySequence.java:39)
        at edu.utexas.cs.nn.tasks.microrts.MicroRTSTask.oneEval(MicroRTSTask.java:210)
        at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:103)
        at edu.utexas.cs.nn.tasks.LonerTask$EvaluationThread.call(LonerTask.java:92)
        at edu.utexas.cs.nn.tasks.LonerTask.evaluateAll(LonerTask.java:207)
        at edu.utexas.cs.nn.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:359)
        at edu.utexas.cs.nn.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:214)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.run(MMNEAT.java:793)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:961)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.main(MMNEAT.java:921)
        ... 5 more

**Comment by alicequint** [comment]
i haven't been able to recreate this issue,
tests with growingEnemySet set to both true and false have been able to change enemies successfully

**Comment by alicequint** [comment]
nevermind, i Was able to recreate this issue! (it only happens when the gensPerEnemy is >1 (this is why i couldnt recreate it in my tests yesterday) and growingEnemySet is true)

**Comment by schrum2** [comment]
Not certain if this is related, but the latest version had another crash at generation 20. See exception below:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArithmeticException: / by zero
        at edu.utexas.cs.nn.tasks.microrts.MicroRTSUtility.oneEval(MicroRTSUtility.java:136)
        at edu.utexas.cs.nn.tasks.microrts.MicroRTSTask.oneEval(MicroRTSTask.java:229)
        at edu.utexas.cs.nn.tasks.NoisyLonerTask.evaluate(NoisyLonerTask.java:103)
        at edu.utexas.cs.nn.tasks.LonerTask$EvaluationThread.call(LonerTask.java:92)
        at edu.utexas.cs.nn.tasks.LonerTask.evaluateAll(LonerTask.java:207)
        at edu.utexas.cs.nn.evolution.mulambda.MuLambda.getNextGeneration(MuLambda.java:362)
        at edu.utexas.cs.nn.experiment.evolution.SinglePopulationGenerationalEAExperiment.run(SinglePopulationGenerationalEAExperiment.java:215)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.run(MMNEAT.java:813)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:981)
        at edu.utexas.cs.nn.MMNEAT.MMNEAT.main(MMNEAT.java:941)
        ... 5 more

**Comment by alicequint** [comment]
yesterday during the day i was running MLPSMCTS-IterativeSet, and it got To generation 20 without crashing by 5, but it seems that it crashed before it got to the next generation.

the stack trace indicates that it's the same / by zero error that caused it before. I'll try toubleshooting it later today

**Comment by alicequint** [comment]
it seems from tests to far that the crash happens on gen 20/21 REGARDLESS of map / enemy switches

**Comment by schrum2** [comment]
Put assertions everywhere in the code indicating what you believe must be true at various points of execution. Use them to help track down where the bug is.

**Comment by alicequint** [comment]
i didnt mean to close this issue in the earlier commit, but now i believe it should be closed anyway. our test has run to generation 24 without crashing!
